# precision, recall, thresholds = precision_recall_curve(y, Ypred)
# area = auc(recall, precision)
# print("Area Under Curve: %0.2f" % area)
# pl.clf()
# pl.plot(recall, precision, label='Precision-Recall curve')
# pl.xlabel('Recall')
# pl.ylabel('Precision')
# pl.ylim([0.0, 1.05])
# pl.xlim([0.0, 1.0])
# pl.title('AUC=%0.2f' % area)
# pl.legend(loc="lower left")
# pl.show()
